### ISSUE TITLE
Out Of Memory error 

### ISSUE THREAD

**Issue by pradeep1806** [kikoso/android-stackblur#39]
Please find  the logs.

E/AndroidRuntime(11680): Caused by: java.lang.OutOfMemoryError: Failed to allocate a 26214412 byte allocation with 13777168 free bytes and 13MB until OOM
E/AndroidRuntime(11680): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
E/AndroidRuntime(11680): 	at android.graphics.Bitmap.nativeCreate(Native Method)
E/AndroidRuntime(11680): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:885)
E/AndroidRuntime(11680): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:909)
E/AndroidRuntime(11680): 	at com.enrique.stackblur.JavaBlurProcess.blur(JavaBlurProcess.java:102)
E/AndroidRuntime(11680): 	at com.enrique.stackblur.StackBlurManager.process(StackBlurManager.java:73)
E/AndroidRuntime(11680): 	at com.micromax.aroundyou.CustomContent$11.doInBackground(CustomContent.java:788)
E/AndroidRuntime(11680): 	at com.micromax.aroundyou.CustomContent$11.doInBackground(CustomContent.java:777)
E/AndroidRuntime(11680): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime(11680): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(11680): 	... 4 more

**Comment by Jawnnypoo** [comment]
So I believe this is an issue with the size of the image. Can you tell me the size of the image?

**Comment by LanderlYoung** [comment]
In my opinion, it is the programmer's responsibility to catch that Error, since any Bitmap operation (eg. decode, create) may raise an OOM.
