### ISSUE TITLE
Can't call getPixels() on a recycled bitmap

### ISSUE THREAD

**Issue by zhangligao999** [kikoso/android-stackblur#46]
when i call stackBlurManager.process(5), error occurs：
 java.lang.IllegalStateException: Can't call getPixels() on a recycled bitmap
                      at android.graphics.Bitmap.checkRecycled(Bitmap.java:383)
                      at android.graphics.Bitmap.getPixels(Bitmap.java:1429)

**Comment by zhangligao999** [comment]
i find the reason, i setDrawingCacheEnabled(false) before process wrongly,
